### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by adc-jasonc** [jeremyosborne/linter-js-tenx#2] opened 2016-04-14 18:50 UTC
[Enter steps to reproduce below:]

1. Open Atom on a non-ten-x project and throw error below

**Atom Version**: 1.7.0
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-js-tenx](https://github.com/jeremyosborne/linter-js-tenx) package, v3.2.7

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Users/jchu/.atom/packages/linter-js-tenx/lib/utils/select-style.js:26

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at getStyleThroughDevDeps (/Users/jchu/.atom/packages/linter-js-tenx/lib/utils/select-style.js:26:42)
    at selectStyle (/Users/jchu/.atom/packages/linter-js-tenx/lib/utils/select-style.js:48:12)
    at Object.module.exports.__cacheTextEditor (/Users/jchu/.atom/packages/linter-js-tenx/lib/init.js:92:17)
    at storeSettings (/Users/jchu/.atom/packages/linter-js-tenx/lib/init.js:64:16)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:379:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:564:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:617:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:692:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:731:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:211:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:10.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:09.5.0 project-manager:list-projects (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:07.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:close (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "linter-jshint",
      "linter-eslint"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "linter-js-tenx": {
    "checkStyleDevDependencies": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
autoclose-html, v0.23.0
linter, v1.11.4
linter-js-tenx, v3.2.7
minimap, v4.21.0
node-debugger, v1.4.7
project-manager, v2.9.7
react, v0.15.0

# Dev
No dev packages
```

**Comment by jeremyosborne** [comment] 2016-04-14 23:02
@adc-jasonc something like this happened to me early on, too, and I don't know exactly why. I did the equivalent of a three finger salute: I closed atom and reopened it and it was fine.

**Comment by adc-jasonc** [comment] 2016-04-14 23:03
Not saying urgent to fix, but good to keep track of this issue.

**Comment by jeremyosborne** [comment] 2016-04-14 23:04
Except I don't get this error is my point. I'm using this plugin myself.

**Comment by jeremyosborne** [comment] 2016-06-17 23:02
Just an update if you guys are still using this. I've been unable to reproduce this error, and have removed some of the original code that was no longer needed that was located in the file that was producing the error. I'll keep an eye on it and try to repro it before the 4.0.0 release, but if I can't repro it will just close.

**Comment by jeremyosborne** [comment] 2016-06-23 02:55
Closing this because as I make use of the plugin and try to break it, I cannot reproduce this error. Please reopen at anytime.

**Closed by jeremyosborne** 2016-06-23 02:55 UTC

**Comment by adc-jasonc** [comment] 2016-06-23 04:29
Thanks. My attention has not caught up on this yet...
